# Development overrides - exposes ports to localhost
services:
  postgres:
    ports:
      - "5432:5432"
    networks:
      - internal
      - default

  redis:
    ports:
      - "6379:6379"
    networks:
      - internal
      - default

networks:
  default:
    driver: bridge
