services:
  # Redis (Job Queue)
  redis:
    image: redis:7-alpine
    container_name: thebox-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: thebox-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-thebox}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-thebox_secret}
      POSTGRES_DB: ${DB_NAME:-thebox}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-thebox}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  # Internal network for database communication
  internal:
    driver: bridge

  # External network for Traefik
  lan:
    external: true
