import type { Knex } from 'knex'

/**
 * Add beginner-friendly achievements to improve user retention and gamification.
 * These achievements are designed to be easily achievable for new players.
 * All names and descriptions are in French (primary language).
 */
export async function up(knex: Knex): Promise<void> {
    // Add new beginner-friendly achievements
    await knex('achievements').insert([
        // === PREMIERS PAS (Gratification immédiate) ===
        {
            key: 'welcome_player',
            name: 'Bienvenue !',
            description: 'Lancez votre premier défi quotidien',
            category: 'completion',
            icon_url: '👋',
            points: 5,
            criteria: JSON.stringify({ type: 'challenges_started', count: 1 }),
            tier: 1,
            is_hidden: false,
        },
        {
            key: 'first_guess',
            name: 'Premier Essai',
            description: 'Faites votre première proposition',
            category: 'completion',
            icon_url: '🎯',
            points: 5,
            criteria: JSON.stringify({ type: 'total_guesses', count: 1 }),
            tier: 1,
            is_hidden: false,
        },
        {
            key: 'first_correct',
            name: 'Œil de Lynx',
            description: 'Trouvez votre première bonne réponse',
            category: 'accuracy',
            icon_url: '✨',
            points: 10,
            criteria: JSON.stringify({ type: 'total_correct_guesses', count: 1 }),
            tier: 1,
            is_hidden: false,
        },

        // === PROGRESSION RAPIDE (Succès en une session) ===
        {
            key: 'getting_warmed_up',
            name: 'Échauffement',
            description: 'Trouvez 3 captures dans un seul défi',
            category: 'accuracy',
            icon_url: '🔥',
            points: 15,
            criteria: JSON.stringify({ type: 'correct_in_game', count: 3 }),
            tier: 1,
            is_hidden: false,
        },
        {
            key: 'halfway_there',
            name: 'À Mi-Chemin',
            description: 'Trouvez 5 captures dans un seul défi',
            category: 'accuracy',
            icon_url: '⭐',
            points: 20,
            criteria: JSON.stringify({ type: 'correct_in_game', count: 5 }),
            tier: 1,
            is_hidden: false,
        },
        {
            key: 'almost_perfect',
            name: 'Presque Parfait',
            description: 'Trouvez 8 captures dans un seul défi',
            category: 'accuracy',
            icon_url: '🌟',
            points: 35,
            criteria: JSON.stringify({ type: 'correct_in_game', count: 8 }),
            tier: 2,
            is_hidden: false,
        },

        // === JALONS DE SCORE (Progressif) ===
        {
            key: 'score_500',
            name: 'Étoile Montante',
            description: 'Obtenez 500+ points dans un seul défi',
            category: 'score',
            icon_url: '📈',
            points: 15,
            criteria: JSON.stringify({ type: 'min_score', score: 500 }),
            tier: 1,
            is_hidden: false,
        },
        {
            key: 'score_1000',
            name: 'En Pleine Forme',
            description: 'Obtenez 1000+ points dans un seul défi',
            category: 'score',
            icon_url: '💪',
            points: 25,
            criteria: JSON.stringify({ type: 'min_score', score: 1000 }),
            tier: 1,
            is_hidden: false,
        },
        {
            key: 'score_1500',
            name: 'Joueur Pro',
            description: 'Obtenez 1500+ points dans un seul défi',
            category: 'score',
            icon_url: '🏆',
            points: 40,
            criteria: JSON.stringify({ type: 'min_score', score: 1500 }),
            tier: 2,
            is_hidden: false,
        },

        // === PARTICIPATION (Engagement) ===
        {
            key: 'regular_player',
            name: 'Joueur Régulier',
            description: 'Complétez 5 défis quotidiens',
            category: 'completion',
            icon_url: '🎮',
            points: 30,
            criteria: JSON.stringify({ type: 'challenges_completed', count: 5 }),
            tier: 1,
            is_hidden: false,
        },
        {
            key: 'committed_gamer',
            name: 'Gamer Assidu',
            description: 'Complétez 10 défis quotidiens',
            category: 'completion',
            icon_url: '🎯',
            points: 50,
            criteria: JSON.stringify({ type: 'challenges_completed', count: 10 }),
            tier: 2,
            is_hidden: false,
        },
        {
            key: 'veteran_player',
            name: 'Joueur Vétéran',
            description: 'Complétez 25 défis quotidiens',
            category: 'completion',
            icon_url: '🎖️',
            points: 100,
            criteria: JSON.stringify({ type: 'challenges_completed', count: 25 }),
            tier: 2,
            is_hidden: false,
        },
        {
            key: 'dedicated_fan',
            name: 'Fan Dévoué',
            description: 'Complétez 50 défis quotidiens',
            category: 'completion',
            icon_url: '💎',
            points: 150,
            criteria: JSON.stringify({ type: 'challenges_completed', count: 50 }),
            tier: 3,
            is_hidden: false,
        },

        // === PROGRESSION CUMULATIVE ===
        {
            key: 'game_collector_10',
            name: 'Collectionneur',
            description: 'Identifiez correctement 10 jeux différents',
            category: 'accuracy',
            icon_url: '📚',
            points: 20,
            criteria: JSON.stringify({ type: 'total_correct_guesses', count: 10 }),
            tier: 1,
            is_hidden: false,
        },
        {
            key: 'game_collector_50',
            name: 'Expert en Jeux',
            description: 'Identifiez correctement 50 jeux différents',
            category: 'accuracy',
            icon_url: '📖',
            points: 75,
            criteria: JSON.stringify({ type: 'total_correct_guesses', count: 50 }),
            tier: 2,
            is_hidden: false,
        },
        {
            key: 'game_collector_100',
            name: 'Encyclopédie Vivante',
            description: 'Identifiez correctement 100 jeux différents',
            category: 'accuracy',
            icon_url: '🏛️',
            points: 150,
            criteria: JSON.stringify({ type: 'total_correct_guesses', count: 100 }),
            tier: 3,
            is_hidden: false,
        },

        // === SÉRIES (Jalons plus accessibles) ===
        {
            key: 'comeback_kid',
            name: 'De Retour',
            description: 'Jouez 2 jours de suite',
            category: 'streak',
            icon_url: '🔄',
            points: 15,
            criteria: JSON.stringify({ type: 'streak', days: 2 }),
            tier: 1,
            is_hidden: false,
        },
        {
            key: 'five_day_streak',
            name: 'Sur une Lancée',
            description: 'Jouez 5 jours de suite',
            category: 'streak',
            icon_url: '🎰',
            points: 40,
            criteria: JSON.stringify({ type: 'streak', days: 5 }),
            tier: 2,
            is_hidden: false,
        },
        {
            key: 'two_week_warrior',
            name: 'Guerrier des Deux Semaines',
            description: 'Jouez 14 jours de suite',
            category: 'streak',
            icon_url: '⚔️',
            points: 125,
            criteria: JSON.stringify({ type: 'streak', days: 14 }),
            tier: 3,
            is_hidden: false,
        },

        // === VITESSE (Entrée plus facile) ===
        {
            key: 'fast_fingers',
            name: 'Doigts Rapides',
            description: 'Répondez en moins de 5 secondes',
            category: 'speed',
            icon_url: '⚡',
            points: 15,
            criteria: JSON.stringify({ type: 'single_speed', count: 1, max_time_ms: 5000 }),
            tier: 1,
            is_hidden: false,
        },
        {
            key: 'speed_collector',
            name: 'Collectionneur de Vitesse',
            description: 'Obtenez 5 réponses rapides (moins de 5 secondes)',
            category: 'speed',
            icon_url: '🏃',
            points: 35,
            criteria: JSON.stringify({ type: 'total_speed', count: 5, max_time_ms: 5000 }),
            tier: 1,
            is_hidden: false,
        },

        // === FUN/CACHÉS ===
        {
            key: 'persistent_guesser',
            name: 'Persévérant',
            description: 'Faites 100 propositions au total',
            category: 'completion',
            icon_url: '💪',
            points: 25,
            criteria: JSON.stringify({ type: 'total_guesses', count: 100 }),
            tier: 1,
            is_hidden: false,
        },
        {
            key: 'guessing_machine',
            name: 'Machine à Deviner',
            description: 'Faites 500 propositions au total',
            category: 'completion',
            icon_url: '🤖',
            points: 75,
            criteria: JSON.stringify({ type: 'total_guesses', count: 500 }),
            tier: 2,
            is_hidden: true,
        },
    ])
}

export async function down(knex: Knex): Promise<void> {
    // Remove the beginner achievements
    await knex('achievements').whereIn('key', [
        'welcome_player',
        'first_guess',
        'first_correct',
        'getting_warmed_up',
        'halfway_there',
        'almost_perfect',
        'score_500',
        'score_1000',
        'score_1500',
        'regular_player',
        'committed_gamer',
        'veteran_player',
        'dedicated_fan',
        'game_collector_10',
        'game_collector_50',
        'game_collector_100',
        'comeback_kid',
        'five_day_streak',
        'two_week_warrior',
        'fast_fingers',
        'speed_collector',
        'persistent_guesser',
        'guessing_machine',
    ]).delete()
}
